services:
    WizaplaceFrontBundle\Service\SitemapGenerator:
        public: false
        autowire: true
        arguments:
            $defaultLocale: '%kernel.default_locale%'
            $locales: '%locales%'
        tags:
            - { name: sitemap.provider }

    sitemap_gz_dumper:
        class: SitemapGenerator\Dumper\GzFileDumper
        arguments: [ "%kernel.root_dir%/../web/sitemap.xml.gz" ]

    sitemap_richxml_formatter:
        class: SitemapGenerator\Formatter\RichXmlFormatter

    sitemap_rich:
        class: SitemapGenerator\Sitemap\Sitemap
        arguments:
            - "@sitemap_gz_dumper"
            - "@sitemap_richxml_formatter"
